services:
  converter:
    image: gotenberg/gotenberg:8
    container_name: webterms-converter
    restart: unless-stopped
    ports:
      - "3001:3000"
    command:
      - gotenberg
      - --api-port=3000
